### ISSUE TITLE
Feature: tests

### ISSUE THREAD

**Issue by stefanwouldgo** [bitcoinprivacy/Bitcoin-Graph-Explorer#3]
set up test suites

**Comment by JorgeMartinezPizarro** [comment]
@stefanwouldgo maybe with the new configuration we can write some scenarios

with a script like that we can create random data like that we can create real edge cases:

```
bitcoind -regtest -daemon

for ((j=1;j<=100;j++));
do
    bitcoin-cli -regtest generate 1
    bitcoin-cli -datadir=/root/.bitcoind/regtest2/ generate 1
    for ((i=1;i<=50;i++));
    do
        a=`bitcoin-cli -datadir=/root/.bitcoin/regtest2/ getnewaddress`
        b=`bitcoin-cli -regtest getnewaddress`
        bitcoin-cli -regtest sendtoaddress $a 0.01
        bitcoin-cli -datadir=/root/.bitcoin/regtest2/ sendtoaddress $b 0.01
    done
done
```

**Comment by JorgeMartinezPizarro** [comment]
@stefanwouldgo  First attemp of test for bge against postgres and bitcoin regtest is added into development. We should discuss about further details.

**Comment by JorgeMartinezPizarro** [comment]
https://bitcoin.org/en/developer-examples#regtest-mode
