### ISSUE TITLE
wrong bge version in api/project/build.scala

### ISSUE THREAD

**Issue by Carcophan** [bitcoinprivacy/Bitcoin-Graph-Explorer#37]
bge version in api/project/build.scala is currently 3.0 which causes the bge/api sbt assembly to fail. Setting this to 3.1 lets the build process complete successfully.

**Comment by JorgeMartinezPizarro** [comment]
Last commit in master branch fixes it

https://github.com/bitcoinprivacy/Bitcoin-Graph-Explorer/commit/0f9eddc26fca46e0b6b473559ba5695ebc567a35
