### ISSUE TITLE
unresolved dependency: net.bitcoinprivacy#bge_2.11;3.1: not found

### ISSUE THREAD

**Issue by tstasevych** [bitcoinprivacy/Bitcoin-Graph-Explorer#43]
Getting error during `sbt stage`:

`[error] (*:update) sbt.ResolveException: unresolved dependency: net.bitcoinprivacy#bge_2.11;3.1: not found
`

Looks like current version is 3.2, but for some reason it is trying to resolve 3.1. Any ideas?

Thanks.

**Comment by stefanwouldgo** [comment]
Sorry, I guess this is in api? Then it is a version conflict between api and bge. Should be fixed in the next commit.
